import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;


public class AlliedRobot {

    private final double defaultTactTime = 1.0;
    Cell pos;
    ArrayList <AllieSequenceRecord> sequence;
    Cell [][] field;

    public AlliedRobot (Cell[][] field, String teamNum, int cargo, double... tactTimeHolder) {

        double tactTime = tactTimeHolder.length == 0 ? defaultTactTime : tactTimeHolder[0];

        Scanner in = new Scanner("");
        try {
            in = new Scanner(new File("Allies_strategies/" + teamNum + ".txt"));
        }
        catch (Exception e) {}
        String currLine;

        in.nextLine();

        sequence = new ArrayList<AllieSequenceRecord>();

        while (true) {
            currLine = in.nextLine().replaceAll("\\(", "").replaceAll(",", "").replaceAll("\\)" , " ");
            Scanner scannedLine = new Scanner(currLine);
            int [] coords = new int[2];
            String action = "";

            try {
                coords[0] = scannedLine.nextInt();
                coords[1] = scannedLine.nextInt();
            } catch (Exception e){
                break;
            }
            if (scannedLine.hasNext()) {
                action = scannedLine.next();
                if (action.equals("l"))
                    cargo ++;
                else if (action.equals("s")) {
                    cargo = 0;
                }
            }

            sequence.add(new AllieSequenceRecord(field[coords[1]][coords[0]], cargo));

            System.out.println(coords[0] + ", " + coords[1] + " " + action);
        }

        for (int i = 0; i < sequence.size() - 1; ++i) {
            AllieSequenceRecord currNode = sequence.get(i), nextNode = sequence.get(i+1);
            sequence.get(i).vel = Vector.CreateFromCartesian(nextNode.cell.x - currNode.cell.x, nextNode.cell.y - currNode.cell.y).dot(1/tactTime);
        }
        sequence.get(sequence.size() - 1).vel = new Vector(0, 0);

        in.close();
    }

    /*public static void main(String[] args) {

        Cell[][] field = {        // w = Wall/obstacle;    l = Loading station;    s = suitable to Shoot;     i = Initiation line
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("l"), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("l"), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("l"), new Cell(" "), new Cell("l"), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("i"), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell("s"), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell(" "), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w")},
                {new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w"), new Cell("w")},
        };

        for (int i = 0; i < field[0].length; ++i) {
            for (int j = 0; j < field.length; ++j) {
                field[j][i].x = i;
                field[j][i].y = j;
            }
        }

        AlliedRobot allie = new AlliedRobot(field, "4290", 3);
    }
*/
}
